#!/usr/bin/env python3
# Generate the full chapters.js file
import os

parts = []

parts.append(r"""// chapters.js
const CHAPTERS=[

// ===== PROLOGUE (10x8) =====
{id:0,title:'序章',subtitle:'墜落之夜',objective:'seize',objectiveDesc:'艾琳到達出口',seizePos:{x:9,y:6},width:10,height:8,
terrain:[
'WWWWGWWWWW',
'WLPPPPPLWW',
'WPWWPPWWPW',
'WPPPLPPPPW',
'WPWWPPWWPW',
'WPPPPPPPPW',
'WLPPPPPLGW',
'WWWWWWWWWW'],
playerUnits:[{charId:'eirine',x:1,y:1},{charId:'marcus',x:1,y:2}],
enemies:[
{classId:'soldier',level:1,x:5,y:1,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:1,x:7,y:2,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:1,x:4,y:3,items:['ironLance'],ai:'defensive',name:'帝國兵'},
{classId:'soldier',level:2,x:8,y:4,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:1,x:3,y:5,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:2,x:6,y:5,items:['ironLance'],ai:'defensive',name:'帝國兵'},
{classId:'knight',level:2,x:8,y:6,items:['ironLance'],ai:'defensive',name:'守衛隊長'}],
npcs:[],newRecruits:[],talkEvents:[],turnEvents:[],
dialogues:{pre:[
{speaker:'eirine',text:'父王……不！我不能離開你！'},
{speaker:null,text:'國王將星印交到艾琳手中，眼中滿是悲傷與決心——'},
{speaker:'marcus',text:'殿下，我們必須離開！宰相莫爾甘的軍隊已經攻入王宮了！'},
{speaker:'eirine',text:'……我明白了。馬庫斯，帶我衝出去！'},
{speaker:'marcus',text:'遵命！請跟緊我，走廊盡頭有一道暗門！'}],
post:[
{speaker:'eirine',text:'我們逃出來了……但父王他……'},
{speaker:'marcus',text:'殿下，先王將一切託付給了您。他的犧牲不能白費。'},
{speaker:'eirine',text:'……是的。我會變強的。為了父王，為了這個國家。'},
{speaker:null,text:'夜色中，兩個身影消失在帝都的城牆之外——'}]}},
""")

parts.append(r"""
// ===== CHAPTER 1 (16x14) =====
{id:1,title:'第一章',subtitle:'荒野的邂逅',objective:'rout',objectiveDesc:'殲滅所有敵人',width:16,height:14,
terrain:[
'PPFFPPPPPPFFPPPP',
'PPFPPPPPPPFPPPPP',
'PPPPPFFPPPPPPFFP',
'FFPPPFFPPPPPPFPP',
'PPPPPPPPPFFFPPPP',
'PPPPVPPPPFPPPPPF',
'PPPPPPPPPPPPPPPP',
'PPPPPPPPPPPPPPPP',
'PPFFFPPPPPPPPPPP',
'PPFPPPPPPPPFFFPP',
'PPPPPPPPPPPPFPPP',
'PPPPPPRRRRPPPPPP',
'PPPPPPRRRPPPPPPP',
'PPPPPPPPPPPPPPPP'],
playerUnits:[{charId:'eirine',x:1,y:11},{charId:'marcus',x:0,y:12}],
newRecruits:[{charId:'lina',x:4,y:5,turnJoin:1}],
enemies:[
{classId:'soldier',level:2,x:10,y:1,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:2,x:12,y:2,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:2,x:14,y:3,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'soldier',level:3,x:13,y:5,items:['ironLance'],ai:'aggressive',name:'帝國兵'},
{classId:'fighter',level:2,x:11,y:6,items:['ironAxe'],ai:'aggressive',name:'傭兵'},
{classId:'fighter',level:2,x:10,y:8,items:['ironAxe'],ai:'aggressive',name:'傭兵'},
{classId:'archer',level:2,x:14,y:4,items:['ironBow'],ai:'defensive',name:'弓兵'},
{classId:'archer',level:2,x:12,y:7,items:['ironBow'],ai:'defensive',name:'弓兵'},
{classId:'soldier',level:3,x:13,y:9,items:['steelLance'],ai:'aggressive',name:'帝國兵'},
{classId:'fighter',level:3,x:9,y:4,items:['ironAxe'],ai:'aggressive',name:'傭兵'},
{classId:'soldier',level:3,x:15,y:6,items:['ironLance'],ai:'defensive',name:'帝國兵'},
{classId:'soldier',level:4,x:14,y:1,items:['steelLance'],ai:'aggressive',name:'追兵隊長',isBoss:true,bonusStats:{hp:3,str:2,def:2}}],
npcs:[],talkEvents:[],
turnEvents:[{turn:1,type:'recruit',text:[
{speaker:'lina',text:'喂！你們是被帝國追殺的人吧？追兵已經從北邊來了。'},
{speaker:'eirine',text:'你是……？'},
{speaker:'lina',text:'叫我莉娜就好。少廢話，先解決眼前的敵人再說。'}]}],
dialogues:{pre:[
{speaker:'marcus',text:'殿下，前方有追兵的蹤跡。我們被跟上了。'},
{speaker:'eirine',text:'……到處都是帝國的人。我們該怎麼辦？'},
{speaker:'marcus',text:'不必慌張。利用森林的掩護，我們可以各個擊破。'},
{speaker:'eirine',text:'好。我不會再逃避了——迎戰！'}],
post:[
{speaker:'lina',text:'解決了。你們還挺能打的嘛。'},
{speaker:'eirine',text:'謝謝你的幫助，莉娜。'},
{speaker:'lina',text:'別謝我。反正我也跟帝國有仇。走吧，這裡不安全。'},
{speaker:'marcus',text:'往北方走。聽說那裡有個村莊可以暫時落腳。'}]}},
""")

parts.append(r"""
// ===== CHAPTER 2 (18x16) =====
{id:2,title:'第二章',subtitle:'北境之村',objective:'survive',objectiveDesc:'堅持8回合',surviveTurns:8,width:18,height:16,
terrain:[
'MMPPPPPPPPPPPPFFMM',
'MPPPPPPPPPPPPPFFMM',
'PPPPPPVPPPVPPPPPPP',
'PPPPPPPPPPPPPPPPPP',
'PPFFFPPPPPPPFFFPPP',
'PPFPPPPPPPPPPFPPPP',
'PPPPPPPPPPPPPPPPPP',
'PPPPPPVPPPPPPPPPPP',
'PPPPPPPPPPPPPPPPPP',
'PPPPPPPPPPPPFFPPPP',
'PPPPPPPPPPPPFFPPPP',
'RRRRRRRRRRRRRRRRPP',
'PPPPPPPPPPPPPPPPPP',
'PPPPPPPPPPPPPPPPPP',
'PPPPPPPPPPPPPPPPPP',
'MMPPPPPPPPPPPPFFMM'],
playerUnits:[{charId:'eirine',x:8,y:5},{charId:'marcus',x:7,y:5},{charId:'lina',x:9,y:5}],
newRecruits:[{charId:'thor',x:6,y:7,turnJoin:1},{charId:'serra',x:7,y:7,turnJoin:1}],
enemies:[
{classId:'brigand',level:3,x:0,y:0,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:3,x:1,y:0,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:4,x:17,y:0,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:3,x:17,y:1,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:3,x:0,y:3,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'fighter',level:4,x:16,y:3,items:['steelAxe'],ai:'aggressive',name:'山賊頭目'},
{classId:'brigand',level:3,x:3,y:0,items:['handAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:3,x:14,y:0,items:['ironAxe'],ai:'aggressive',name:'山賊'}],
npcs:[],talkEvents:[],
turnEvents:[
{turn:1,type:'recruit',text:[
{speaker:'thor',text:'哈哈哈！你們來得正好！我正愁沒人幫忙呢！'},
{speaker:'serra',text:'請幫幫這個村莊的人們……我是賽拉，教會的修女。'},
{speaker:'eirine',text:'當然！我們一起保護村莊！'}]},
{turn:3,type:'reinforce',enemies:[
{classId:'brigand',level:3,x:0,y:15,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:4,x:1,y:15,items:['steelAxe'],ai:'aggressive',name:'山賊頭目'},
{classId:'brigand',level:3,x:17,y:15,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:3,x:16,y:15,items:['handAxe'],ai:'aggressive',name:'山賊'}]},
{turn:5,type:'reinforce',enemies:[
{classId:'brigand',level:4,x:0,y:0,items:['steelAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:4,x:17,y:0,items:['handAxe'],ai:'aggressive',name:'山賊'},
{classId:'fighter',level:5,x:0,y:15,items:['steelAxe'],ai:'aggressive',name:'山賊頭領'},
{classId:'fighter',level:5,x:17,y:15,items:['steelAxe'],ai:'aggressive',name:'山賊頭領'}]},
{turn:7,type:'reinforce',enemies:[
{classId:'brigand',level:4,x:0,y:8,items:['ironAxe'],ai:'aggressive',name:'山賊'},
{classId:'brigand',level:4,x:17,y:8,items:['ironAxe'],ai:'aggressive',name:'山賊'}]}],
dialogues:{pre:[
{speaker:'eirine',text:'前方的村莊——有人在呼救！'},
{speaker:'marcus',text:'山賊正在包圍村莊。殿下，我們必須守住。'},
{speaker:'eirine',text:'那裡的人們……我們一定要保護他們！'},
{speaker:'lina',text:'敵人從四面八方來。集中在村莊附近防守比較好。'},
{speaker:'marcus',text:'同意。利用河流作為天然屏障，守住北岸。'}],
post:[
{speaker:'thor',text:'哈哈！打得痛快！你們真不錯！算我一個！'},
{speaker:'serra',text:'殿下……您為了素昧平生的人而戰，真是高尚。請讓我跟隨您。'},
{speaker:'eirine',text:'謝謝你們。只要大家團結，一定能度過難關。'}]}},
""")

parts.append(r"""
// ===== CHAPTER 3 (16x14) =====
{id:3,title:'第三章',subtitle:'傭兵的代價',objective:'rout',objectiveDesc:'說服凱恩並殲滅敵人',width:16,height:14,
terrain:[
'MMPPPPPPPPPPMMPP',
'MPPPPPPPPPPPMMPF',
'PPPPPPPPPPPPPPPP',
'PPPPRRRPPPPPPPPP',
'PPPPRRRPPPPPPPPP',
'PPPPRRPPPPPPFFPP',
'PPPGGGPPPPPPPFPP',
'PPPPPPPPPPPPPPPP',
'PPPPPPPPFFPPPPPP',
'PPPPPPPPFFPPPPPP',
'PPPPPPPPPPPPPPPP',
'PPFPPPPPPPPPPFPP',
'PPFFPPPPPPPPPFPP',
'PPPPPPPPPPPPPPPP'],
playerUnits:[{charId:'eirine',x:1,y:12},{charId:'marcus',x:0,y:12},{charId:'lina',x:2,y:13},{charId:'thor',x:1,y:13},{charId:'serra',x:0,y:13}],
newRecruits:[],
enemies:[
{classId:'mercenary',level:5,x:8,y:1,items:['ironSword'],ai:'aggressive',name:'凱恩',isCain:true,recruitableBy:'eirine'},
{classId:'soldier',level:4,x:10,y:0,items:['ironLance'],ai:'aggressive',name:'傭兵團員'},
{classId:'soldier',level:4,x:12,y:1,items:['ironLance'],ai:'aggressive',name:'傭兵團員'},
{classId:'fighter',level:4,x:14,y:2,items:['ironAxe'],ai:'aggressive',name:'傭兵團員'},
{classId:'fighter',level:4,x:13,y:3,items:['ironAxe'],ai:'aggressive',name:'傭兵團員'},
{classId:'archer',level:4,x:15,y:1,items:['ironBow'],ai:'defensive',name:'傭兵弓手'},
{classId:'archer',level:4,x:11,y:3,items:['ironBow'],ai:'defensive',name:'傭兵弓手'},
{classId:'soldier',level:5,x:10,y:4,items:['steelLance'],ai:'aggressive',name:'傭兵隊長'},
{classId:'soldier',level:4,x:13,y:5,items:['ironLance'],ai:'aggressive',name:'傭兵團員'},
{classId:'fighter',level:4,x:12,y:6,items:['ironAxe'],ai:'aggressive',name:'傭兵團員'},
{classId:'soldier',level:4,x:15,y:5,items:['ironLance'],ai:'aggressive',name:'傭兵團員'},
{classId:'fighter',level:5,x:14,y:7,items:['steelAxe'],ai:'aggressive',name:'傭兵精銳'},
{classId:'soldier',level:4,x:11,y:8,items:['ironLance'],ai:'aggressive',name:'傭兵團員'}],
npcs:[],
talkEvents:[{from:'eirine',target:'cain',dialogue:[
{speaker:'eirine',text:'凱恩！停手！你不必為帝國賣命！'},
{speaker:'cain',text:'哦？帝國公主殿下……你知道我多少錢一天嗎？'},
{speaker:'eirine',text:'我出不起錢，但我能給你一個值得為之戰鬥的理由。'},
{speaker:'cain',text:'……哈，有意思。好吧，就陪你玩玩看。反正那個僱主也欠了我三個月薪水了。'}]}],
turnEvents:[],
dialogues:{pre:[
{speaker:'marcus',text:'殿下，前方峽谷有一隊傭兵擋路。他們似乎是受僱來截殺我們的。'},
{speaker:'eirine',text:'傭兵……也許我可以跟他們的首領談談。'},
{speaker:'lina',text:'跟傭兵講道理？你真是天真。'},
{speaker:'eirine',text:'不試試怎麼知道呢？有時候，劍解決不了的事，言語可以。'},
{speaker:'thor',text:'嘿，如果談不攏，就用斧頭說話！'}],
post:[
{speaker:'cain',text:'哼，正義什麼的……可不能當飯吃。不過……你的眼神倒是不像在說謊。'},
{speaker:'eirine',text:'歡迎加入，凱恩。'},
{speaker:'lina',text:'切，又多了一個吃飯的嘴。'},
{speaker:'cain',text:'放心，我的劍比我的飯量值錢得多。'}]}},
""")

parts.append(r"""
// ===== CHAPTER 4 (14x18) =====
{id:4,title:'第四章',subtitle:'魔法塔',objective:'seize',objectiveDesc:'艾琳到達塔頂',seizePos:{x:6,y:0},width:14,height:18,
terrain:[
'WWWWWWGWWWWWWW',
'WLPPPPPPPPPLWW',
'WPWWWPPWWWPPWW',
'WPPPPPPPPPPPWW',
'WWPPWWWWPPWWWW',
'WLPPPPPPPPPLWW',
'WPWWWPPWWWPPWW',
'WPPPPPPPPPPPWW',
'WWPPWWWWPPWWWW',
'WLPPPPPPPPPLWW',
'WPWWWPPWWWPPWW',
'WPPPPPPPPPPPWW',
'WWPPWWWWPPWWWW',
'WLPPPPPPPPPLWW',
'WPPPPPPPPPPPWW',
'WPWWWPPWWWPPWW',
'WPPPPPPPPPPPWW',
'WWWWWWGWWWWWWW'],
playerUnits:[{charId:'eirine',x:6,y:17},{charId:'marcus',x:5,y:16},{charId:'lina',x:7,y:16},{charId:'thor',x:6,y:16},{charId:'serra',x:5,y:15},{charId:'cain',x:7,y:15}],
newRecruits:[{charId:'fran',x:7,y:1,turnJoin:1}],
enemies:[
{classId:'mage',level:6,x:3,y:14,items:['fire'],ai:'defensive',name:'魔法師'},
{classId:'mage',level:6,x:10,y:14,items:['thunder'],ai:'defensive',name:'魔法師'},
{classId:'skeleton',level:5,x:1,y:13,items:['ironLance'],ai:'aggressive',name:'骷髏兵'},
{classId:'skeleton',level:5,x:12,y:13,items:['ironAxe'],ai:'aggressive',name:'骷髏兵'},
{classId:'mage',level:6,x:3,y:11,items:['wind'],ai:'defensive',name:'魔法師'},
{classId:'mage',level:7,x:10,y:11,items:['fire'],ai:'aggressive',name:'魔法師'},
{classId:'skeleton',level:5,x:1,y:9,items:['ironAxe'],ai:'aggressive',name:'骷髏兵'},
{classId:'skeleton',level:6,x:12,y:9,items:['ironLance'],ai:'aggressive',name:'骷髏兵'},
{classId:'mage',level:7,x:3,y:7,items:['elfire'],ai:'defensive',name:'上級魔法師'},
{classId:'mage',level:7,x:10,y:7,items:['elthunder'],ai:'defensive',name:'上級魔法師'},
{classId:'mage',level:7,x:1,y:5,items:['fire'],ai:'aggressive',name:'魔法師'},
{classId:'mage',level:7,x:12,y:5,items:['thunder'],ai:'aggressive',name:'魔法師'},
{classId:'skeleton',level:6,x:3,y:3,items:['ironAxe'],ai:'defensive',name:'骷髏兵'},
{classId:'skeleton',level:6,x:10,y:3,items:['ironLance'],ai:'defensive',name:'骷髏兵'},
{classId:'mage',level:7,x:4,y:1,items:['fire'],ai:'defensive',name:'魔法師'},
{classId:'darkMage',level:8,x:6,y:1,items:['flux'],ai:'boss',name:'暗黑祭司',isBoss:true,bonusStats:{hp:8,mag:4,skl:3,spd:2,def:3,res:4}}],
npcs:[],talkEvents:[],
turnEvents:[
{turn:1,type:'recruit',text:[
{speaker:'fran',text:'哈哈哈！又有人闖進本天才的塔了？'},
{speaker:'eirine',text:'我們不是敵人！我是——'},
{speaker:'fran',text:'帝國公主艾琳？有意思！好吧，讓本天才來助你一臂之力！'}]},
{turn:4,type:'reinforce',enemies:[
{classId:'skeleton',level:6,x:1,y:17,items:['ironAxe'],ai:'aggressive',name:'骷髏兵'},
{classId:'skeleton',level:6,x:12,y:17,items:['ironLance'],ai:'aggressive',name:'骷髏兵'}]}],
dialogues:{pre:[
{speaker:'eirine',text:'這就是傳說中的魔法塔……據說裡面住著一位天才魔法師。'},
{speaker:'marcus',text:'這座塔被暗黑魔物佔據了。殿下，請小心。'},
{speaker:'lina',text:'裡面到處都是魔法師和亡靈……真是個鬼地方。'},
{speaker:'thor',text:'哼！不管是鬼還是骷髏，一斧頭下去都一樣！'},
{speaker:'cain',text:'魔法攻擊無視物理防禦，注意走位。'}],
post:[
{speaker:'fran',text:'不錯嘛，能打到這裡。我是法蘭，史上最強的年輕天才魔法師！'},
{speaker:'lina',text:'……自稱天才的人通常不是天才。'},
{speaker:'fran',text:'什麼！？你——'},
{speaker:'eirine',text:'好了好了。法蘭，謝謝你的幫助。一起走吧。'}]}},
""")

parts.append(r"""
// ===== CHAPTER 5 (20x18) =====
{id:5,title:'第五章',subtitle:'星辰要塞',objective:'boss',objectiveDesc:'擊敗要塞守將',width:20,height:18,
terrain:[
'PPPPPPPPPPPPPPPPPPPP',
'PPPPFFPPPPPPFFPPPPPP',
'PPPPFFPPPPPPFFPPPPPP',
'PPPPPPPPPPPPPPPPPPPP',
'PPPPPPPPVPPPPPPPPPPP',
'PPPPPPPPPPPPPPPPPPPP',
'PPRRRRRRRRRRRRRRRRPP',
'PPRRRRRRRRRRRRRRRRPP',
'PPPPPPPPGGPPPPPPPPPP',
'PPPPPPWWWWWWPPPPPPPP',
'PPPPWWWLPPWWWWPPPPPP',
'PPPPWPPPPPPPPWPPPPPP',
'PPPPWPLPPPPLPWPPPPPP',
'PPPPWPPPPPPPPWPPPPPP',
'PPPPWWPPPPPPWWPPPPPP',
'PPPPPWWLTTLWWPPPPPPP',
'PPPPPWWWWWWWWPPPPPPP',
'PPPPPPPPPPPPPPPPPPPP'],
playerUnits:[{charId:'eirine',x:9,y:0},{charId:'marcus',x:8,y:0},{charId:'lina',x:10,y:0},{charId:'thor',x:9,y:1},{charId:'serra',x:8,y:1},{charId:'cain',x:10,y:1},{charId:'fran',x:11,y:1}],
newRecruits:[{charId:'rex',x:15,y:3,turnJoin:2}],
enemies:[
{classId:'soldier',level:7,x:8,y:8,items:['steelLance'],ai:'defensive',name:'要塞守兵'},
{classId:'soldier',level:7,x:11,y:8,items:['steelLance'],ai:'defensive',name:'要塞守兵'},
{classId:'knight',level:7,x:6,y:10,items:['steelLance'],ai:'defensive',name:'重裝兵'},
{classId:'knight',level:7,x:13,y:10,items:['steelLance'],ai:'defensive',name:'重裝兵'},
{classId:'archer',level:7,x:5,y:9,items:['steelBow'],ai:'defensive',name:'要塞弓兵'},
{classId:'archer',level:7,x:14,y:9,items:['steelBow'],ai:'defensive',name:'要塞弓兵'},
{classId:'mage',level:7,x:7,y:12,items:['elfire'],ai:'defensive',name:'要塞魔法師'},
{classId:'mage',level:7,x:12,y:12,items:['elthunder'],ai:'defensive',name:'要塞魔法師'},
{classId:'soldier',level:8,x:5,y:11,items:['steelLance'],ai:'aggressive',name:'要塞守兵'},
{classId:'soldier',level:8,x:14,y:11,items:['steelLance'],ai:'aggressive',name:'要塞守兵'},
{classId:'knight',level:8,x:8,y:14,items:['steelLance'],ai:'defensive',name:'近衛兵'},
{classId:'knight',level:8,x:11,y:14,items:['steelLance'],ai:'defensive',name:'近衛兵'},
{classId:'fighter',level:7,x:3,y:7,items:['steelAxe'],ai:'aggressive',name:'守衛'},
{classId:'fighter',level:7,x:16,y:7,items:['steelAxe'],ai:'aggressive',name:'守衛'},
{classId:'archer',level:8,x:9,y:13,items:['steelBow'],ai:'defensive',name:'精銳弓兵'},
{classId:'paladin',level:1,x:9,y:15,items:['silverLance','javelin'],ai:'boss',name:'要塞守將格倫',isBoss:true,bonusStats:{hp:10,str:3,skl:2,spd:2,def:4,res:2}},
{classId:'soldier',level:8,x:10,y:15,items:['steelLance'],ai:'defensive',name:'護衛兵'}],
npcs:[],talkEvents:[],
turnEvents:[
{turn:2,type:'recruit',text:[
{speaker:'rex',text:'艾琳殿下！我是飛龍騎士團副團長雷克斯！帝國的暴行我再也看不下去了！'},
{speaker:'eirine',text:'雷克斯……太好了，有你的幫助，我們一定能攻下這座要塞！'}]},
{turn:4,type:'reinforce',enemies:[
{classId:'soldier',level:7,x:0,y:9,items:['ironLance'],ai:'aggressive',name:'增援兵'},
{classId:'soldier',level:7,x:19,y:9,items:['ironLance'],ai:'aggressive',name:'增援兵'},
{classId:'archer',level:7,x:0,y:10,items:['ironBow'],ai:'aggressive',name:'增援弓兵'}]}],
dialogues:{pre:[
{speaker:'eirine',text:'這座要塞擋住了我們前進的道路。必須攻下它。'},
{speaker:'marcus',text:'要塞前有一條河流，只有中央的橋門可以通過。'},
{speaker:'cain',text:'別衝太快，裡面的守軍不是省油的燈。'},
{speaker:'serra',text:'我會在後方治療大家